# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rw_mh_theta_cpp_impl <- function(k, m = 10000L, w = 0.10, x0 = 0.50) {
    .Call(`_SA25168238_rw_mh_theta_cpp_impl`, k, m, w, x0)
}

